INSERT INTO USUARIO (id,nome,idade) VALUES (1, 'DOUGLAS', 33);
INSERT INTO USUARIO (id,nome,idade) VALUES (2, 'ALLINE', 32);
INSERT INTO USUARIO (id,nome,idade) VALUES (3, 'GIOVANNA', 1);
INSERT INTO USUARIO (id,nome,idade) VALUES (4, 'EDNEUSA', 61);
INSERT INTO USUARIO (id,nome,idade) VALUES (5, 'GENESIO', 70);
INSERT INTO USUARIO (id,nome,idade) VALUES (6, 'JULIO', 93);
INSERT INTO USUARIO (id,nome,idade) VALUES (7, 'CONCEICAO', 91);